apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-testing
  namespace: testing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-api-testing
  template:
    metadata:
      labels:
        app: node-api-testing
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command: ['sh', '-c', 'until nc -z mysql-service.testing 3306; do echo waiting for mysql; sleep 2; done;']
      containers:
      - name: node-api
        image: node-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_HOST
          value: "mysql-service.testing"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "mydb"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5