apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-staging
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-api-staging
  template:
    metadata:
      labels:
        app: node-api-staging
    spec:
      containers:
      - name: node-api
        image: node-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_HOST
          value: "mysql-service.staging"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "mydb"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5